package GUI;

import code.CustomException;
import code.FileStorage;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.event.WindowEvent;
import java.util.ArrayList;

public class CreateBus extends javax.swing.JFrame {
    DefaultListModel jListModel = new DefaultListModel();
    private static String edit = "false";

    /**
     * Creates new form CreateBus
     */
    public CreateBus() {
        initComponents();
        jLabel10.setVisible(false);
        searchBusID.setVisible(false);
        searchBtn.setVisible(false);
        deleteBusBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        busID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        originDropMenu = new javax.swing.JComboBox<>();
        destinationDropMenu = new javax.swing.JComboBox<>();
        distance = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        hrDropMenu = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        minsDropMenu = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        timetableMenu = new javax.swing.JList<>();
        addBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        farePerKM = new javax.swing.JTextField();
        fare = new javax.swing.JLabel();
        show_validation_here = new javax.swing.JLabel();
        seatsDropMenu = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        searchBusID = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        deleteBusBtn = new javax.swing.JButton();

        setTitle("Bus Ticket Reservation - Create Bus");
        setResizable(false);
        setSize(new java.awt.Dimension(750, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bus ID");

        busID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        busID.setText("--");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Origin");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Destination");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Fare/KM");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Seats");

        originDropMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        originDropMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                originDropMenuItemStateChanged(evt);
            }
        });
        originDropMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originDropMenuActionPerformed(evt);
            }
        });

        destinationDropMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"-- Destination --"}));
        destinationDropMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                destinationDropMenuItemStateChanged(evt);
            }
        });
        destinationDropMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationDropMenuActionPerformed(evt);
            }
        });

        distance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        distance.setText("--");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Distance");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Fare");

        saveBtn.setText("Save");
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });

        hrDropMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " "}));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Times");

        minsDropMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55"}));

        timetableMenu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Null"};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        jScrollPane2.setViewportView(timetableMenu);

        addBtn.setText("Add");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Timetable");

        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });

//        farePerKM.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                farePerKMActionPerformed(evt);
//            }
//        });
//        farePerKM.addKeyListener(new java.awt.event.KeyAdapter() {
//            public void keyPressed(java.awt.event.KeyEvent evt) {
//                farePerKMKeyPressed(evt);
//            }
//        });
        farePerKM.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                calculateFarePerKM();
            }

            public void removeUpdate(DocumentEvent e) {
                calculateFarePerKM();
            }

            public void insertUpdate(DocumentEvent e) {
                calculateFarePerKM();
            }
        });
        fare.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fare.setText("--");

        show_validation_here.setForeground(new java.awt.Color(255, 0, 0));

        seatsDropMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"30", "45", "60"}));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Search with busID");

        searchBusID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBusIDActionPerformed(evt);
            }
        });
        searchBusID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchBusIDKeyPressed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });

        deleteBusBtn.setText("Delete");
        deleteBusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBusBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(286, 286, 286))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(89, 89, 89)
                                                                .addComponent(jLabel9)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(hrDropMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(minsDropMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(addBtn))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(427, 427, 427)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel8)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(89, 89, 89)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(jLabel7))
                                                                .addGap(17, 17, 17)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(originDropMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(farePerKM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                        .addComponent(seatsDropMenu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(show_validation_here, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                                                                .addGap(111, 111, 111)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel5)
                                                                                        .addComponent(jLabel22))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(fare)
                                                                                        .addComponent(distance)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel10)
                                                                                .addGap(28, 28, 28)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel1)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(busID))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(searchBusID, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(searchBtn)
                                                                                                .addGap(7, 7, 7)
                                                                                                .addComponent(deleteBusBtn)))))))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(deleteBtn)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(523, 523, 523)
                                                .addComponent(destinationDropMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(searchBusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchBtn)
                                        .addComponent(deleteBusBtn))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(busID)
                                        .addComponent(jLabel1))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(originDropMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(65, 65, 65)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(farePerKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(show_validation_here, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(seatsDropMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(41, 41, 41)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                        .addComponent(hrDropMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(minsDropMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(addBtn)
                                                        .addComponent(jLabel8))
                                                .addGap(35, 35, 35)
                                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(destinationDropMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(distance))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(44, 44, 44)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel22)
                                                                        .addComponent(fare)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(deleteBtn)))
                                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void calculateFarePerKM() {
        try {
            int FPKM = Integer.parseInt(farePerKM.getText());
            int D = Integer.parseInt(distance.getText());
            show_validation_here.setText(" ");
            fare.setText(String.valueOf(FPKM * D));
        } catch (NumberFormatException e) {
            show_validation_here.setText("Invalid Number");
            e.getMessage();
        }
    }

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        // TODO add your handling code here:
        boolean valid = true;
        if (originDropMenu.getSelectedItem().toString().equals("-- Select Origin --")
                || destinationDropMenu.getSelectedItem().toString().equals("-- Destination --")
                || distance.getText().equals("--")) {
            valid = false;
            JOptionPane.showMessageDialog(null, "Pick an origin and destination.");
        }
        if (fare.getText().equals("--")) {
            valid = false;
            JOptionPane.showMessageDialog(null, "Enter a fare/km and press enter");
        }
        if (timetableMenu.getModel().getSize() == 0) {
            valid = false;
            JOptionPane.showMessageDialog(null, "At least one time is required.");
        }

        if (valid) {
            try {
                String[] data = new String[6 + timetableMenu.getModel().getSize()];
                data[0] = String.valueOf((Integer.parseInt(FileStorage.getLastId("buses")) + 1));
                data[1] = originDropMenu.getSelectedItem().toString();
                data[2] = destinationDropMenu.getSelectedItem().toString();
                data[3] = distance.getText();
                data[4] = fare.getText();
                data[5] = seatsDropMenu.getSelectedItem().toString();
                for (int i = 6; i < data.length; i++) {
                    data[i] = (String) jListModel.getElementAt(i - 6);
                }
                if (edit.equals("true")) {
                    data[0] = busID.getText();
                    FileStorage.updateRecord("buses", data[0], data);
                    JOptionPane.showMessageDialog(null, "Bus Updated");
                } else {
                    FileStorage.addRecord("buses", data);
                    JOptionPane.showMessageDialog(null, "Bus Created");
                }
                dispose();
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_saveBtnMouseClicked

    private void formWindowOpened(WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        timetableMenu.setModel(jListModel);
        ArrayList<String> Origin = new ArrayList<>();
        try {
            ArrayList<String[]> rows = FileStorage.readData("cities");
            for (String[] row : rows) {
                if (!Origin.contains(row[1])) {
                    Origin.add(row[1]);
                }
            }
        } catch (Exception e) {
        }
        String[] originArr = new String[Origin.size()];
        originArr = Origin.toArray(originArr);

        originArr[0] = "-- Select Origin --";
        DefaultComboBoxModel originModel = new DefaultComboBoxModel(originArr);
        originDropMenu.setModel(originModel);
        if (edit.equals("true")) {
            setTitle("Bus Ticket Reservation - Edit Bus");
            jLabel10.setVisible(true);
            searchBusID.setVisible(true);
            searchBtn.setVisible(true);
            deleteBusBtn.setVisible(true);
        } else {
            try {
                Integer ID = (Integer.parseInt(FileStorage.getLastId("buses")) + 1);
                busID.setText(String.valueOf(ID));
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void originDropMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_originDropMenuItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_originDropMenuItemStateChanged

    private void originDropMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originDropMenuActionPerformed
        // TODO add your handling code here:
        ArrayList<String> Destination = new ArrayList<>();
        Destination.add("-- Destination --");
        try {
            ArrayList<String[]> rows = FileStorage.readData("cities");
            for (String[] row : rows) {
                if (originDropMenu.getSelectedItem().toString().equals((row[1]))) {
                    Destination.add(row[2]);
                }
            }
        } catch (Exception e) {
        }
        String[] destArr = new String[Destination.size()];
        destArr = Destination.toArray(destArr);
        DefaultComboBoxModel destModel = new DefaultComboBoxModel(destArr);
        destinationDropMenu.setModel(destModel);
    }//GEN-LAST:event_originDropMenuActionPerformed

    private void destinationDropMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_destinationDropMenuItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationDropMenuItemStateChanged

    private void destinationDropMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationDropMenuActionPerformed
        // TODO add your handling code here:
        try {
            ArrayList<String[]> rows = FileStorage.readData("cities");
            for (String[] row : rows) {
                if (destinationDropMenu.getSelectedItem().toString().equals((row[2])) && originDropMenu.getSelectedItem().toString().equals(row[1])) {
                    distance.setText(row[3]);
                    if (edit.equals("true")) {
                        int FPKM = Integer.parseInt(farePerKM.getText());
                        int D = Integer.parseInt(distance.getText());
                        fare.setText(String.valueOf(D * FPKM));
                    }
                }
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_destinationDropMenuActionPerformed

    private void farePerKMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_farePerKMKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_farePerKMKeyPressed

    private void farePerKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farePerKMActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_farePerKMActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // TODO add your handling code here:
        if (timetableMenu.getModel().getSize() != 0) {
            jListModel.removeElementAt(timetableMenu.getSelectedIndex());
        }
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void farePerKMPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_farePerKMPropertyChange
        // TODO add your handling code here:


    }//GEN-LAST:event_farePerKMPropertyChange

    private void checkIfExist(String searchTerm) throws CustomException {
        if (jListModel.contains(searchTerm)) {
            throw new CustomException(null,"Time already exist");
        }
    }

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        try {
            String text = hrDropMenu.getSelectedItem().toString() + ":" + minsDropMenu.getSelectedItem().toString();
            checkIfExist(text);
            jListModel.addElement(text);
        } catch (CustomException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_addBtnMouseClicked

    private void searchBusIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBusIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBusIDActionPerformed

    private void searchBusIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBusIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBusIDKeyPressed

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        if (!searchBusID.getText().equals("")) {
            try {
                ArrayList<String[]> buses = FileStorage.readData("buses");
                boolean found = false;
                for (String[] bus : buses) {
                    if (bus[0].equals(searchBusID.getText())) {
                        busID.setText(bus[0]);
                        originDropMenu.setSelectedItem(bus[1]);
                        destinationDropMenu.setSelectedItem(bus[2]);
                        distance.setText(bus[3]);
                        fare.setText(bus[4]);
                        farePerKM.setText(String.valueOf(Integer.parseInt(fare.getText()) / Integer.parseInt(distance.getText())));
                        seatsDropMenu.setSelectedItem(bus[5]);
                        jListModel.removeAllElements();
                        for (int i = 6; i < bus.length; i++) {
                            jListModel.addElement(bus[i]);
                        }
                        found = true;
                    }
                }
                if (!found) {
                    JOptionPane.showMessageDialog(null, "No bus with this ID found");
                }
            } catch (Exception e) {
            }
        } else JOptionPane.showMessageDialog(null, "Can't be empty");
    }//GEN-LAST:event_searchBtnMouseClicked

    private void deleteBusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBusBtnMouseClicked
        if (!searchBusID.getText().equals("") && !busID.getText().equals("--")) {
            try {
                String id = busID.getText();
                int x = JOptionPane.showConfirmDialog(null, "Confirm and delete ?", "Delete bus", JOptionPane.YES_NO_OPTION);
                if (x == JOptionPane.YES_OPTION) {
                    FileStorage.deleteRecord("buses", id);
                    JOptionPane.showMessageDialog(null, "Bus NO.( " + id + " ) deleted.");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Nothing deleted");
                }
            } catch (Exception e) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Press Search first");
        }
    }//GEN-LAST:event_deleteBusBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        if (args[0].equals("true")) {
            edit = "true";
        } else edit = "false";
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel busID;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteBusBtn;
    private javax.swing.JComboBox<String> destinationDropMenu;
    private javax.swing.JLabel distance;
    private javax.swing.JLabel fare;
    private javax.swing.JTextField farePerKM;
    private javax.swing.JComboBox<String> hrDropMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> minsDropMenu;
    private javax.swing.JComboBox<String> originDropMenu;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchBusID;
    private javax.swing.JComboBox<String> seatsDropMenu;
    private javax.swing.JLabel show_validation_here;
    private javax.swing.JList<String> timetableMenu;
    // End of variables declaration//GEN-END:variables
}